### ISSUE TITLE
Another weird `path must not be empty` error

### ISSUE THREAD

**Issue by yikeke** [banyan/auto-label#27]
hi thanks for your great work on this action. Could you please provide some help on an error I ran into?

I'm using yml file like this:

```
name: Auto Label
on:
  pull_request:
    branches:
      - 'release-*'
    types: [opened]

jobs:
  auto-label:
    name: Auto Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: banyan/auto-label@1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

and get `path must not be empty` error.

My error log is:

```
Run banyan/auto-label@1.2
  with:
    configPath: .github/auto-label.json
  env:
    GITHUB_TOKEN: ***
##[error]path must not be empty
```

My json file is:

{
  "rules": {
    "status/PTAL": ["*.md", "*.yml", "*.yaml", "*.json", "media/", "scripts/"]
  }
}

My PR link: https://github.com/pingcap/docs-cn/pull/3631. Any clue on this? @banyan
