### ISSUE TITLE
Getting error "config file does not exist."

### ISSUE THREAD

**Issue by rkpatel33** [banyan/auto-label#7]
I am getting this error regarding the config file not existing, even though its in the repo at the following path:

```
.github/auto-label.json
```

Wondering if you might have any ideas on this, would love to be able to use your workflow. 

![image](https://user-images.githubusercontent.com/3799489/66894012-40a8f380-efa4-11e9-8dc8-2719bb0d0a2a.png)

My setup looks like the following:

`.github/auto-label.json`:

```js
{
  "rules": {
    "Instant": ["instant/*"],
    "Investing": ["investing/*"],
    "MissionControl": ["support/*"],
    "migrations": ["*/migrations/*"]
  }
}
```

`.github/workflows/labelling-workflow.yml`:

```yml
name: Labelling workflow

on:
  pull_request:
    paths:
    - '**.py'
    - '**.json'

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: auto-label
        uses: banyan/auto-label@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # This step prints an output (time) from the previous step's action.
      - name: Echo auto-label's time
        run: echo 'The time was ${{ steps.auto-label.outputs.time }}.'
```
